{"name": "Проверка создания уже зарегестрированного пользователя", "status": "passed", "attachments": [{"name": "stdout", "source": "472b85bc-b510-4be0-8809-fc5881e63776-attachment.txt", "type": "text/plain"}], "start": 1712519892343, "stop": 1712519893343, "uuid": "7ad917eb-a748-4770-afa1-8649edf96a0c", "historyId": "a0c744c8bbb5e28c86edb4b0b3d0cd43", "testCaseId": "a0c744c8bbb5e28c86edb4b0b3d0cd43", "fullName": "tests.test_create_new_user.TestCreateNewUser#test_create_new_user_with_existing_data_error_403", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_new_user"}, {"name": "subSuite", "value": "TestCreateNewUser"}, {"name": "host", "value": "WIN-R1RFFME11IE"}, {"name": "thread", "value": "7708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_new_user"}]}